[project]
name = "ai-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "albumentations>=2.0.8",
    "django>=5.2.5",
    "openai>=1.99.9",
    "pyqt6>=6.9.1",
    "ultralytics>=8.3.176",
]
